// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHcbo0dqhVkpxF8q7t09wh-n9juDIauRg',
    appId: '1:638524143029:web:4c2d17be90b6f9a7d915fc',
    messagingSenderId: '638524143029',
    projectId: 'notify-dd676',
    authDomain: 'notify-dd676.firebaseapp.com',
    storageBucket: 'notify-dd676.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3QlX0BXAgXpFUrcovda9aDMqIePXqcoQ',
    appId: '1:638524143029:android:aafec2d8ce80b10dd915fc',
    messagingSenderId: '638524143029',
    projectId: 'notify-dd676',
    storageBucket: 'notify-dd676.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHTrmfOWwAxVYGd1ebMWprUmU-1NUu_xM',
    appId: '1:638524143029:ios:6d7e9ae5c0b39a23d915fc',
    messagingSenderId: '638524143029',
    projectId: 'notify-dd676',
    storageBucket: 'notify-dd676.appspot.com',
    iosBundleId: 'com.example.bechduPartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHTrmfOWwAxVYGd1ebMWprUmU-1NUu_xM',
    appId: '1:638524143029:ios:eebe6b987cddef0ad915fc',
    messagingSenderId: '638524143029',
    projectId: 'notify-dd676',
    storageBucket: 'notify-dd676.appspot.com',
    iosBundleId: 'com.example.bechduPartner.RunnerTests',
  );
}
